version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 737f1214f58fa1201c6500ef92592c3762f79718b2d17c581851c38ca501d0a7

    working_directory: ~/slovensko-digital/harvester.ecosystem

    docker:
      - image: circleci/ruby:2.5.0-node-browsers
        environment:
          RAILS_ENV: test

      - image: circleci/postgres:9.6.8-alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_PASSWORD: ''

    steps:
      - checkout
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./test-reporter
      - run: chmod +x ./test-reporter
      - run: sudo apt-get install postgresql-client
      - restore_cache: { keys: ['{{ checksum "Gemfile.lock" }}'] }
      - run: bundle install --path vendor/bundle
      - save_cache: { key: '{{ checksum "Gemfile.lock" }}', paths: [vendor/bundle] }
      - run: dockerize -wait tcp://localhost:5432 -timeout 60s
      - run: mv .circleci/database.yml config/database.yml
      - run: bundle exec rake db:create db:structure:load --trace
      - run: ./test-reporter before-build
      - run: bundle exec rspec
      - run: ./test-reporter after-build --coverage-input-type simplecov --exit-code $?
