service:
  enabled: false
ingress:
  enabled: false
image:
  secrets:
  - name: skdigital-bonet-registry
livenessProbe:
  initialDelaySeconds: 5
  timeoutSeconds: 10
  probeType: "exec"
  command:
    - "pgrep"
    - "bundle"
readinessProbe:
  probeType: "exec"
  command:
    - "pgrep"
    - "bundle"
application:
  migrateCommand: ["bundle", "exec", "rails", "db:migrate"]
  command: ["bundle", "exec", "clockwork", "config/clock.rb"]
resources:
  requests:
    cpu: 10m
    memory: 100Mi
  limits:
    memory: 200Mi
workers:
  worker:
    replicaCount: "1"
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    terminationGracePeriodSeconds: 60
    livenessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 10
      probeType: "exec"
      command:
        - "pgrep"
        - "bundle"
    readinessProbe:
      probeType: "exec"
      command:
        - "pgrep"
        - "bundle"
    resources:
      requests:
        cpu: 1
        memory: 2.5Gi
      limits:
        memory: 2.5Gi
