name: Deploy accessories to Staging

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  staging-accessories-deploy:
    name: Deploy accessories to staging environment
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Kamal gem
        run: gem install kamal -v '~> 2.6'

      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEV_DEPLOY_KEY }}

      - name: Deploy accessories
        env:
          KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}

        run: kamal accessory reboot redis -d staging
